hostname: 'sharat-1.centie.net.au'
port: 8080
dpid: 6
base_url: 'stats/'

prometheus:
    join_delim: ':'
    port: 4545

csvwriter:
    dir: 'data/test/'

data_type:
    port:
        enable: true
        filter:
            key: 'port_no'
            values: [4,5,6,7]
        endpoints:
            counters:
                url: 'port/<dpid>'
                interval: 8
                labels:
                    - 'port_no'
                values:
                    - 'rx_packets'
                    - 'rx_bytes'
                    - 'rx_errors'
                    - 'tx_packets'
                    - 'tx_bytes'
                    - 'tx_errors'

    flow:
        enable: true
        endpoints:
          counters:
              url: 'flow/<dpid>'
              interval: 5
              labels:
                  - 'table_id'
                  - 'cookie'
              values:
                  - 'byte_count'
                  - 'packet_count'
                  - 'duration_sec'
                  - 'duration_nsec'
    group:
        enable: true
        endpoints:
          counters:
              url: 'group/<dpid>'
              interval: 5
              labels:
                  - 'group_id'
              values:
                  - 'byte_count'
                  - 'packet_count'
                  - 'duration_sec'
                  - 'duration_nsec'
                  - 'ref_count'

    queue:
        enable: false
        filter:
            key: 'queue_id'
            values: [0,1,2,3]
        common_labels:
          - 'queue_id'
          - 'port_no'
        endpoints:
          counters:
            url: 'queue/<dpid>/7' #7->port_no
            interval: 1
            labels:
                - 'queue_id'
                - 'port_no'
            values:
                - 'tx_bytes'
                - 'tx_packets' 
                - 'tx_errors'       
          config:
              url: 'queueconfig/<dpid>/7' #7->port_no
              interval: 1
              labels:
                - 'queue_id'
                - 'port_no'
              values:
                - 'min_rate'
                - 'max_rate'

    meter:
        enable: false
        filter:
            key: 'meter_id'
            values: [1,2,3]
        endpoints:
            counters:
                url: 'meter/<dpid>'
                interval: 1
                labels:
                    - 'meter_id'
                values:
                    - 'duration_nsec'
                    - 'duration_sec'
                    - 'byte_in_count'
                    - 'flow_count'
                    - 'packet_in_count'
                    - 'band_<i>_byte_band_count'
                    - 'band_<i>_packet_band_count'
            config:
                url: 'meterconfig/<dpid>'
                interval: 1
                labels:
                    - meter_id
                values:
                    - 'band_<i>_type'
                    - 'band_<i>_rate'
                    - 'band_<i>_burst_size'
